# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "journal"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "jn"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
crossterm = "0.27"
anyhow = "1.0.70"
chrono = "0.4.24"
clap = { version = "4.4.11", features = ["derive"] }
directories = "5.0.0"
toml = "0.8.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
regex = "1.0.0"
tokio = { version = "1.35.0", features = ["full"] }
aws-config = "1.1.1"
aws-sdk-s3 = "1.8.0"
ring = "0.17.7"
data-encoding = "2.5.0"
rustyline = "13.0.0"
zip = "0.6.6"
inquire = "0.6.2"
