# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "journal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jn"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
crossterm = "0.26"
anyhow = "1.0.70"
chrono = "0.4.24"
clap = { version = "4.1.13", features = ["derive"] }
directories = "5.0.0"
toml = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.95"
regex = "1.0.0"
tokio = { version = "1.33.0", features = ["full"] }
aws-config = "0.56.1"
aws-sdk-s3 = "0.33.0"
ring = "0.17.5"
data-encoding = "2.4.0"
rustyline = "12.0.0"
zip = "0.6.6"
