# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "journal"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "jn"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
crossterm = "0.27"
anyhow = "1.0.79"
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
directories = "5.0.0"
toml = "0.8.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.113"
regex = "1.10.3"
ring = "0.17.7"
data-encoding = "2.5.0"
rustyline = "13.0.0"
zip = "0.6.6"
inquire = "0.6.2"
